import "../index.css"
// import "./obserbables/fromexample"
// import "./obserbables/01-observables"
// import "./obserbables/02-unsubscribe"
// import "./obserbables/03-of"
//import "./obserbables/04-from"
// import "./obserbables/05-fromeven"
// import "./operadores/01-map_pluck_mapTo"
// import "./operadores/02-filter"
// import "./operadores/03-tap"
import "./operadores/04-map-lab"
